theme: jekyll-theme-merlot
title: Métricas de Calidad Interna y Externa para Servicios Cloud: Un Mapeo Sistemático
description: Articulo de Metricas de Calidad Interna y Externa para Servicios Cloud presentado a JISBD 2019
